### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Silex**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks, but this isn't a typo: "iff" has a specific meaning in computer science - https://en.wikipedia.org/wiki/Iff

**Comment by Silex** [comment]
Oh, hehe then thanks for enlightening me :)

**Comment by purcell** [comment]
Some days I like "iff", and some days I don't. This is at least the 2nd PR I've received to correct it as a typo, so it's probably not such a valuable word that it's worth confusing people. :-)

**Comment by Silex** [comment]
I guess you could write it as `IFF` to denote the acronym. That or `if and only if` but it's longer to type :)

**Comment by purcell** [comment]
Yes, I should simply type the latter, and stop being lazy. :-)

**Pull request closed without merging**
